version: '3.8'

services:
  app:
    build: .
    container_name: xodimlar_app
    volumes:
      - .:/var/www
    depends_on:
      - database
    environment:
      DATABASE_URL: "mysql://xodimlar:secret@database:3306/xodimlar?serverVersion=8.0&charset=utf8mb4"
    networks:
      - xodimlar_net

  nginx:
    image: nginx:alpine
    container_name: xodimlar_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - xodimlar_net

  database:
    image: mysql:8.0
    container_name: xodimlar_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: xodimlar
      MYSQL_USER: xodimlar
      MYSQL_PASSWORD: secret
    ports:
      - "33061:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - xodimlar_net

volumes:
  db_data:


networks:
  xodimlar_net:
