services:
  app:
    build: .
    container_name: xodimlar_app
    volumes:
      - .:/var/www
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://xodimlar:secret@db:3306/xodimlar?serverVersion=8.0&charset=utf8mb4"
    networks:
      - xodimlar_net

  nginx:
    image: nginx:alpine
    container_name: xodimlar_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - xodimlar_net

  db:
    image: mysql:8.0
    container_name: xodimlar_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: xodimlar
      MYSQL_USER: xodimlar
      MYSQL_PASSWORD: secret
    ports:
      - "33060:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - xodimlar_net

volumes:
  db_data:

networks:
  xodimlar_net:
